### ISSUE TITLE
Basic PvP stat tracking

### ISSUE THREAD

**Issue by Zach443** [BattlePlugins/BattleTracker-3.0#1]
This is pretty much the most important thing for BattleTracker... Basic SQL stat tracking for events within BattleArena.

This should include tracking per player for: 
- [x] Kills
- [x] Deaths
- [ ] ~~Wins~~
- [ ] ~~Losses~~
- [x] Kill/Death and Win/Loss ratios

Server wide stat tracking will include: 
- [x] Leaderboards for each of the above categories

And then of course UUID support from the start for all of these things 😄

**Comment by Redned235** [comment]
Wins/Losses will be handled inside of BattleArena by extending the Tracker class and implementing its own tracking. The SQL storage system will allow for custom columns (in BattleArena's case, wins/losses).

BattleArena will not only handle Wins/Losses like it currently does, but it will also handle Kills/Deaths so that information can be compared and tracked as well.
